version: '3'
services:
  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - 3000:3000
    environment:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: postgres
      GF_DATABASE_NAME: grafana
      GF_DATABASE_USER: grafana
      GF_DATABASE_PASSWORD: grafana

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: grafana
      POSTGRES_PASSWORD: grafana
      POSTGRES_DB: grafana
